version: '3.9'

services:
  app:
    image: 'library:latest'
    build:
      context: ""
    container_name: app
    ports:
      - 8087:8087
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
      POSTGRES_INITDB_ARGS: -A md5
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all