version: '3.9'

services:
  app:
    image: 'library:latest'
    build:
      ../
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
      - localstack
    environment:
      AWS_LOCALSTACK_HOSTNAME: http://localstack:4566
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure

  db:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
      POSTGRES_INITDB_ARGS: -A md5
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all

  localstack:
    image: localstack/localstack:0.12.9.1
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
    ports:
      - 4566:4566

