spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aa1k1vc51hery8g.cacy5nbno7zy.eu-central-1.rds.amazonaws.com:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jwt:
  token:
    secret: ghshjs3672382h22j3h2