spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    validate-on-migrate: true
    user: postgres
    password: postgres
    schemas: library_db