spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/library_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jwt:
  token:
    secret: ghshjs3672382h22j3h2

aws:
  s3-bucket: bucket
